### ISSUE TITLE
[FR] Helper methods for triggering 'local' save/load events 

### ISSUE THREAD

**Issue by Lordfirespeed** [MaxWasUnavailable/LethalModDataLib#1]
Allowing mods to arbitrarily trigger load events could be problematic.

That said, "do everything that a load/save event would have done **to my instance/class**" will emerge as a common pattern (for example, when instantiating prefabs after the initial session load event). 

Some new convenience API is proposed, for example:
```cs
ModDataHelper.TriggerLoad(this)
ModDataHelper.TriggerSave(this, SaveType.AutoSave)
ModDataHelper.TriggerSave(this, SaveType.OnSave)
```

**Comment by MaxWasUnavailable** [comment]
Will add, planned for next feature release.
