### ISSUE TITLE
Issue with playing

### ISSUE THREAD

**Issue by xCichy879x** [MaxWasUnavailable/LethalModDataLib#12]
Umm, I installed newly updated LethalLevelloader mod [V50], so I can play on SecretLabs moon. 
While installing it on Thunderstore app, this LethalModDataLib was installed with it and some other.
When I started the game on my save file, the game is unplayable. 
And I know that it's because of LethalModDataLib, because when I disable it, everything works but only that SecretLabs moon don't work.
And I tried changing the version of this LMDL mod, but the same thing happens. So I thought that in files there must be an issue, but I have no idea. I tried to look on Thunderstore webside of mod if there are some informations that I don't know of. I didn't find nothing usefull. 
Please help.

![20240425095707_1](https://github.com/MaxWasUnavailable/LethalModDataLib/assets/168072831/fd14b0e7-8137-4f16-bb3e-5249e4875fba)

**Comment by MaxWasUnavailable** [comment]
This might be an issue with LethalLevelLoader's usage of the mod. Could you provide your logs? Preferably with debug enabled.

**Comment by xCichy879x** [comment]
Sorry, How I can do this?

**Comment by MaxWasUnavailable** [comment]
In your BepInEx folder (in the game directory) is a log file. There is also a config folder there, in which you can find the BepInEx config.

**Comment by xCichy879x** [comment]
Funny, I did one thing... I started the game, and it works now, but some other mods do not work.

**Comment by xCichy879x** [comment]
[
[LogOutput.log](https://github.com/MaxWasUnavailable/LethalModDataLib/files/15152021/LogOutput.log)
](url)

Is it this what you wanted?

**Comment by MaxWasUnavailable** [comment]
Yup! For future reference, you can open these with any text editor, and search through the file for any instances of "error". It seems OpenMonitors is causing a *lot* of errors, so might be at cause. No errors with my mod that I can see.
