### ISSUE TITLE
Mod Messes up save and switches items for new ones

### ISSUE THREAD

**Issue by rominemaster** [MaxWasUnavailable/LethalModDataLib#13]
I got this mod with LLL and when we tried to play a game we saw our save got messed up and all our flashlights were walkie talkies, all our shovels were apparatices, ect. Every time we closed the server and reopened the save the items would switch up again.

We're using the latest version of both Lethal Level Loader and LethlModDataLib.

**Comment by MaxWasUnavailable** [comment]
This is an issue with LLL. LethalModDataLib does __not__ do anything functional on its own, nor does it touch vanilla save files.
