### ISSUE TITLE
[FR] re-usable `SaveConfiguration`

### ISSUE THREAD

**Issue by Lordfirespeed** [MaxWasUnavailable/LethalModDataLib#4]
![image](https://github.com/MaxWasUnavailable/LethalModDataLib/assets/28568841/9beb73a6-9d78-489e-b2d8-19b56e20c723)

**Comment by MaxWasUnavailable** [comment]
Will look into doing this before first public release, to prevent potential backwards breaking / other weirdness

**Comment by MaxWasUnavailable** [comment]
Obsolete constructor will eventually be removed, once I've had time to better integrate the new ModDataConfiguration object.

**Comment by MaxWasUnavailable** [comment]
Reversed since this is not actually possible in CSharp.
