### ISSUE TITLE
Verify multiplayer behaviour correctness

### ISSUE THREAD

**Issue by Lordfirespeed** [MaxWasUnavailable/LethalModDataLib#5]
### For the host
- `CurrentSave` data should be saved/loaded as usual
- `GeneralSave` data should be saved/loaded as usual

### For all clients
- `CurrentSave` data should **not** be saved/loaded 
- `GeneralSave` data should be saved/loaded as usual

**Comment by MaxWasUnavailable** [comment]
Needs to be fixed before release
